# Rubocop configuration that MUST hold for every build.

inherit_from: rubocop-todo.yml

AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
    - spec/**

ClassLength:
  Max: 185  # Try to reduce this value

MethodLength:
  Max: 18  # Try to reduce this value

CyclomaticComplexity:
  Max: 8  # Try to reduce this value

LineLength:
  Max: 115  # Try to reduce this value