language: ruby
env:
  global:
    - HEADLESS=true
    - RAILS_DB_ADAPTER=mysql2
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
install:
  - sed -i "s/^\(gem .mysql2.\),.*$/\1/" Gemfile
  - bundle install --path vendor/bundle
  - bundle update mysql2
script:
  - bundle exec rake db:create ci --trace
