language: ruby
env:
  - HEADLESS=true
  - RAILS_DB_ADAPTER=mysql2
rvm:
  - 2.1.7
  - 2.2.3
install:
  - sed -i "s/^\(gem .mysql2.\),.*$/\1/" Gemfile
  - bundle install --path vendor/bundle
script:
  - rake db:create ci --trace
