

phone_number:
  predefined_labels: 
    - Privat
    - Mobil
    - Arbeit
    - Vater
    - Mutter
    - Fax
    - Andere
    
social_account:
  predefined_labels:
    - Skype
    - Webseite
    - MSN

email:
  # Sender for all emails sent by the application
  sender: jubla+noreply@puzzle.ch

  # If mass emails are sent, this recipient is used in the to field,
  # while the actual recipients go in the bcc field.
  mass_recipient: jubla@puzzle.ch
  
  # configuration for retrieving email
  retriever:
    type: pop3
    config:
      address:    localhost
      port:       995
      user_name:  nil
      password:   nil
      enable_ssl: true

# The person with this email has root access to everything
# This person should only be used by the operators of the application, not the customers.
root_email: jubla@puzzle.ch

# Presets for PDF labels
pdf:
  labels:
    font_name: Helvetica
    ignored_countries:
      - ch
      - schweiz
      
# Presets for CSV export
csv:
  separator: ;

role:
  # If a role last less than this number of days, it is not archived
  minimum_days_to_archive: 7