

phone_number:
  predefined_labels: 
    - Privat
    - Mobil
    - Arbeit
    - Vater
    - Mutter
    - Fax
    - Andere
    
social_account:
  predefined_labels:
    - E-Mail
    - Facebook
    - MSN
    - Skype
    - Twitter
    - Webseite

email:
  # Sender for all emails sent by the application
  sender: noreply@jubla.ch

  # If mass emails are sent, this recipient is used in the to field,
  # while the actual recipients go in the bcc field.
  mass_recipient: noreply@jubla.ch
  
  # domain where mailing lists are located
  list_domain: <%= ENV['RAILS_HOST_NAME'] || 'localhost' %>
  
  # configuration for retrieving email
  retriever:
    type: pop3
    # interval to check for new mails in minutes
    interval: 3
    config:
      address:    <%= ENV['RAILS_MAIL_RETRIEVER_ADDRESS'] || 'localhost' %>
      port:       <%= ENV['RAILS_MAIL_RETRIEVER_PORT'] || 995 %>
      user_name:  <%= ENV['RAILS_MAIL_RETRIEVER_USER'] %>
      password:   <%= ENV['RAILS_MAIL_RETRIEVER_PASSWORD'] %>
      enable_ssl: <%= %w(true yes 1).include?(ENV['RAILS_MAIL_RETRIEVER_SSL']) %>

# The person with this email has root access to everything
# This person should only be used by the operators of the application, not the customers.
root_email: jubla@puzzle.ch

# Presets for PDF labels
pdf:
  labels:
    font_name: Helvetica

# Preset for addresses
address:
  ignored_countries:
    - ch
    - schweiz
      
# Presets for CSV export
csv:
  separator: ;

role:
  # If a role last less than this number of days, it is not archived
  minimum_days_to_archive: 7
