

phone_number:
  predefined_labels: 
    - Privat
    - Mobil
    - Arbeit
    - Vater
    - Mutter
    - Fax
    - Andere
    
social_account:
  predefined_labels:
    - Skype
    - Webseite
    - MSN

# Sender for all emails sent by the application
email_sender: jubla+noreply@puzzle.ch

# If mass emails are sent, this recipient is used in the to field,
# while the actual recipients go in the bcc field.
email_mass_recipient: jubla@puzzle.ch


pdf:
  labels:
    font_name: Helvetica
    ignored_countries:
      - ch
      - schweiz
      
csv:
  separator: ;

role:
  # If a role last less than this number of days, it is not archived
  minimum_days_to_archive: 7