name: 'Rails Lint and Test'
env:
  DB_USER: hitobito
  DB_PASSWORD: hitobito
  DB_NAME: hitobito_test
  DB_PORT: 33066

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      HEADLESS: true
      RAILS_DB_ADAPTER: mysql2
      RAILS_DB_HOST: 127.0.0.1

    services:
      mysql:
        image: 'mysql:5.7'
        env:
          MYSQL_USER: '${{ env.DB_USER }}'
          MYSQL_PASSWORD: '${{ env.DB_PASSWORD }}'
          MYSQL_DATABASE: '${{ env.DB_NAME }}'
        ports:
          - '${{ env.DB_PORT }}:3306'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: 'memcached'
        ports: [ '11211:11211' ]

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1.59.1
        env:
          ImageOS: ubuntu18

      - name: 'Setup OS'
        run: |
          sudo apt-get -qq update
          sudo apt-get install sphinxsearch

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 'Bundle install'
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: 'Yarn install'
        run: |
          yarn install --frozen-lockfile

      - name: 'Run Webpacker'
        env:
          RAILS_DB_PORT: '${{ env.DB_PORT }}'
          RAILS_DB_USERNAME: '${{ env.DB_USER }}'
          RAILS_DB_PASSWORD: '${{ env.DB_PASSWORD }}'
          RAILS_DB_NAME: '${{ env.DB_NAME }}'
          RAILS_TEST_DB_NAME: '${{ env.DB_NAME }}'
        run: |
          bundle exec rake webpacker:compile

      - name: 'Run Lint and Tests'
        env:
          RAILS_DB_PORT: '${{ env.DB_PORT }}'
          RAILS_DB_USERNAME: '${{ env.DB_USER }}'
          RAILS_DB_PASSWORD: '${{ env.DB_PASSWORD }}'
          RAILS_DB_NAME: '${{ env.DB_NAME }}'
          RAILS_TEST_DB_NAME: '${{ env.DB_NAME }}'
        run: |
          bundle exec rake db:create ci --trace
