name: 'Rails Lint and Test'

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      HEADLESS: true
      RAILS_DB_ADAPTER: mysql2
      RAILS_DB_HOST: 127.0.0.1
      RAILS_DB_PORT: 33066
      RAILS_DB_USERNAME: hitobito
      RAILS_DB_PASSWORD: hitobito
      RAILS_DB_NAME: hitobito_test
      RAILS_TEST_DB_NAME: hitobito_test

    services:
      mysql:
        image: 'mysql:5.7'
        env:
          MYSQL_USER: 'hitobito'
          MYSQL_PASSWORD: 'hitobito'
          MYSQL_DATABASE: 'hitobito_test'
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '33066:3306'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: 'memcached'
        ports: [ '11211:11211' ]

    steps:
      - name: 'Setup OS'
        run: |
          sudo apt-get -qq update
          sudo apt-get install sphinxsearch gawk

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Fix Gemfile.lock for CI'
        run: |
          gawk -i inplace '/GEM/{f=1}f' Gemfile.lock
          gawk -i inplace '{gsub("ruby$", "x86_64-linux", $0); print}' Gemfile.lock
          git diff Gemfile.lock || true

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1.59.1
        with:
          bundler-cache: true
        env:
          ImageOS: ubuntu18

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: 'Yarn install'
        run: |
          yarn install --frozen-lockfile

      - name: 'Run Webpacker'
        run: |
          bundle exec rake webpacker:compile

      - name: 'Run Lint and Tests'
        run: |
          bundle exec rake db:create ci --trace
